apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --build local
    kompose.image-pull-policy: Never
    kompose.service.type: nodeport
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api
  type: NodePort
