apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1  # Reduced from 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nslookup db.default.svc.cluster.local; do echo waiting for db; sleep 2; done;']
      containers:
      - name: api
        image: us-central1-docker.pkg.dev/model-ripple-467310-c7/my-repo/api:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_CONNECTION_STRING
          value: "mongodb://db.default.svc.cluster.local:27017/dockerApp"
        resources:
          requests:
            cpu: "100m"  # Reduced from 500m
            memory: "512Mi"  # Reduced from 2Gi
            ephemeral-storage: "1Gi"
          limits:
            ephemeral-storage: "1Gi"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10